# Generated by Django 4.0.6 on 2022-11-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kinodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('kateqoriya', models.CharField(max_length=50)),
                ('il', models.CharField(max_length=20)),
                ('reytinq', models.CharField(max_length=50)),
                ('foto', models.CharField(max_length=50)),
                ('dil', models.CharField(max_length=100)),
                ('rejissor', models.CharField(max_length=50)),
                ('melumat', models.CharField(max_length=5000)),
                ('video_link', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
            ],
        ),
    ]
