# Generated by Django 4.0.6 on 2022-11-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
