# Generated by Django 4.0.6 on 2022-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ad',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='tarix',
            field=models.DateField(auto_now=True),
        ),
    ]
