# Generated by Django 4.0.6 on 2022-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_ad_comment_tarix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kinodata',
            old_name='rejissor',
            new_name='category',
        ),
        migrations.AddField(
            model_name='kinodata',
            name='runtime',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
