# Generated by Django 4.0.6 on 2022-12-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_rejissor_kinodata_category_kinodata_runtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kinodata',
            old_name='kateqoriya',
            new_name='company',
        ),
    ]
