# Generated by Django 4.0.6 on 2023-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_kateqoriya_kinodata_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('page', models.IntegerField()),
            ],
        ),
    ]
